name: deploy

on:
  push:
    paths-ignore:
      - "LICENSE"
      - "README.md"
      - ".gitignore"
    branches:
      - main
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "production"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

permissions:
  contents: read

# set an environment variable for use in the jobs pointing to my site
env:
  web_url: https://blog.birki.io/

jobs:
  deployment-check:
    runs-on: ubuntu-latest
    outputs: # set outputs for use in downstream jobs
      continue: ${{ steps.deployment-check.outputs.continue }}

    steps:
      # https://github.com/github/branch-deploy/blob/d3c24bd92505e623615b75ffdfac5ed5259adbdb/docs/merge-commit-strategy.md
      - name: deployment check
        uses: github/branch-deploy@v10
        id: deployment-check
        with:
          merge_deploy_mode: "true"
          environment: production

  build:
    if: ${{ needs.deployment-check.outputs.continue == 'true' }}
    needs: deployment-check
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set hugo version
        id: hugo-version
        run: |
          HUGO_VERSION=$(cat .hugo-version)
          echo "HUGO_VERSION=${HUGO_VERSION}" >> $GITHUB_OUTPUT

      - name: install vendored hugo cli
        env:
          HUGO_VERSION: ${{ steps.hugo-version.outputs.HUGO_VERSION }}
        run: sudo dpkg -i vendor/hugo_extended_${HUGO_VERSION}_linux-amd64.deb

      - name: build with hugo
        run: hugo --gc --logLevel info --baseURL ${{ env.web_url }}

      - name: write build version
        run: echo ${GITHUB_SHA} > ./public/version.txt

      # upload the built site as an artifact for the deploy step
      - uses: actions/upload-artifact@v4
        with:
          name: site-artifact
          path: ./public

  deploy:
    if: ${{ needs.deployment-check.outputs.continue == 'true' }}
    needs: [ deployment-check, build ]
    environment:
      name: production
      url: ${{ env.web_url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site-artifact
          path: ./public

      # deploy the site to cloudflare pages
      - name: deploy
        id: deployment
        uses: cloudflare/wrangler-action@7a5f8bbdfeedcde38e6777a50fe685f89259d4ca # pin@v3.13.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          wranglerVersion: '3.9.0'
          command: pages deploy public/ --project-name=blog-birki-io --branch=main
